### ISSUE TITLE
Store attached CSVs, link to them if available

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/aggregate#102]
opendatakit/xforms-spec#94 describes a standard for specifying that a client should generate an audit trace for a specific form and for specifying the audit csv filename in the submission.

In the Aggregate table view, the user should be able to click on the audit filename to see a popup with the audit contents the same way that he/she can click on an image to get a popup with the image.

A form for testing: [audit-test-orx.xml.txt](https://github.com/opendatakit/aggregate/files/1285353/audit-test-orx.xml.txt)

**Comment by dcbriccetti** [comment]
A simpler form:

[shorter-audit-test-orx.xml.txt](https://github.com/opendatakit/aggregate/files/1364277/shorter-audit-test-orx.xml.txt)

**Comment by ggalmazor** [comment]
Can this issue be closed? @yanokwa @lognaturel

**Comment by lognaturel** [comment]
Absolutely. Looks like "solves" is not a [keyword for closing issues](https://help.github.com/articles/closing-issues-using-keywords/) so that's why it didn't close automatically!
