### ISSUE TITLE
Submodules contain Eclipse project and settings files

### ISSUE THREAD

**Issue by brmeyer** [opendatakit/aggregate#103]
Most submodules contain Eclipse's `.project`, `.settings`, and `.classpath` files/dirs.  Generally, these shouldn't be controlled and are mostly specific to each user's workspace and IDE setup.  If there is anything specific in those files that would be needed to import/build, migrate it the Maven POMs (IDE agnostic if possible, but m2e plugin config otherwise).

**Comment by yanokwa** [comment]
Fixed by #112
