### ISSUE TITLE
Re-architect the modules with clear separation between service/business src and infrastructure

### ISSUE THREAD

**Issue by brmeyer** [opendatakit/aggregate#105]
Morning!  I'm hoping to help think through what it would look like to re-architect the project setup, with a primary goal: Make it as easy as possible for new and existing contributors to be effective.  The following is purely a WIP that I'll keep adding to as I go through the project.  These are purely suggestions based on approaches I've used in past lives, but I'd love feedback from others!

Some inspiration is drawn from https://github.com/ArtificerRepo/artificer, which is an artifact and metadata repository I used to be involved with @ Red Hat.  That project has a lot of warts and I'm definitely not claiming it to be a perfect role model.  But we ran into similar issues: various src layers, concurrent support for numerous environments/containers (some of which require substantial config and artifact changes), integration test harnesses, tooling, clients, etc., all while remaining IDE-agnostic and attempting to make new contributions as easy as possible.  Success is arguable ;), but there were some steps in the right direction.

- /aggregate
  - /aggregate-src
    - _`aggregate-src` currently exists, but it's only a POM that refers to the `src` dir back at the top level.  This pulls together all service, business, etc. src -- likely most non-test and non-infra code -- into a jar that can be used as a dependency by infra modules._
    - _Note that aggregate-src could/should be broken down into additional modules, each its on jar and usable as a dependency.  As is, the code base is fairly large.  Plus, this is helpful for composibility, if separation of concerns is currently possible._
    - Artifact: jar
    - /src (main and unit test)
  - /server
    - /api
      - _Houses any Servlet classes, controllers, or any "API" src that's specific to the generic application server._
      - Dependencies: aggregate-src, servlet-api
      - Artifact: jar
    - all Tomcat, GAE, etc. specific submodules
      - _Isolate all container-specific configuration, dependencies, and dynamic tasks (Ant or otherwise)._
      - Dependencies: aggregate-src, api, container-specific dependencies
      - Artifact: specific to the container (war, ear, etc.)
    - /dev-server
      - _Provides a harness that's primarily for developers, giving a simple way to kickoff an embedded server (Tomcat/Jetty/Undertow) that automatically pulls in necessary deps and jars/wars.  Likely resembles the other container-specific submodules, but super stripped down.  This may be what some of the Eclipse-specific bits are doing now, but in an IDE-agnostic way.  Easily used from any IDE run config._
  - /integration-test
    - _Isolate all integration test projects here (most are currently in `/aggregate/src/it`)._
    - _I need to look more into the it src itself, so I'm firing from the hip with this one.  But, it's typically helpful to provide additional separation: it source + 1..n submodules containing harnesses and bootstrapping for any supported environment/db._
  - /doc
  - /installer
    - _Likely most of `bitrock-installer` in its current form, but tweaked to grab the new artifacts._

Some of these could potentially be broken out into separate repos altogether.

**Comment by ggalmazor** [comment]
Hi!

Just wanted to tell that I've created PR #112 with a proposal to migrate the project to Gradle. I've tried to document what's been done and would love to have your feedback and thoughts about it.

Thanks!

**Comment by yanokwa** [comment]
Close by #112
