### ISSUE TITLE
Creating LDAP user with phpldapadmin with sync-endpoint-containers

### ISSUE THREAD

**Issue by farrukharshad** [opendatakit/aggregate#108]
Greetings,
 
I have build the docker container [sync-endpoint-container](https://github.com/opendatakit/sync-endpoint-containers). I have followed exact instructions as mentioned above and to run the odk services I have followed [these](https://github.com/opendatakit/sync-endpoint-default-setup) instructions. All the services run fine, but when the above instructions suggest to create an LDAP user [here](https://github.com/opendatakit/sync-endpoint-default-setup#ldap) I can not login to admin. If I provide username "admin" and password "admin" I see the error 

Unable to connect to LDAP server ldap-service
Error: Invalid DN syntax (34) for user
Failed to Authenticate to server
Invalid Username or Password.

All my configurations are default, but I am accessing phpldapadmin via its IP address and not localhost. 

If I try to login to odk-web-ui there again admin/admin does not work.

Thanks

**Comment by linl33** [comment]
`admin` is just the cn, you need to supply the full dn `cn=admin,dc=example,dc=org`

**Comment by farrukharshad** [comment]
Thanks.

**Comment by farrukharshad** [comment]
I have created the account but I can not login to the application with that account via odk-web-ui ?

**Comment by linl33** [comment]
You should be able to use the accounts in your LDAP directory to login. 

Make sure that you use the `uid` (or the attribute configured in `security.properties`) of the user to login, not the dn. The users should also need to be in appropriate groups.
