### ISSUE TITLE
Installation error when running Java 1.9

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#113]
On macOS, installing ODK Aggregate throws a NoClassDefFoundError error.

https://forum.opendatakit.org/t/odk-aggregate-installation-error-on-mac-sierra/10232
https://forum.opendatakit.org/t/odk-aggregate-installer-failure-on-macos/9978

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
@yanokwa could you check if this is still happening with the new installer?

**Comment by yanokwa** [comment]
I am still getting this problem. To reproduce, I did the following..

1. Put `org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home` in my properties so gradle uses Java 8 to compile. It can't compile with Java 9.
1. Run `./gradlew clean build -x test -PwarMode=installer && ./gradlew buildInstaller`
1. Use InstallBuilder to generate an installer.
1. Run the installer and have it launch the uploader.

<img width="504" alt="screen shot 2017-12-08 at 15 08 05" src="https://user-images.githubusercontent.com/32369/33788870-9c6e45fc-dc29-11e7-9858-2bca7f0da63f.png">

```
$ java -jar ODKAggregateAppEngineUpdater.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more
```
```
$ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
Veritas:~/Desktop/ODK Aggregate >
```

**Comment by yanokwa** [comment]
The problem is with ODKAggregateAppEngineUpdater and the code for that lives here: https://github.com/opendatakit/aggregate-components. 

I haven't thought about this deeply, but since that app seems core to Aggregate, maybe we can move that code into this repo and then try to fix it?

Tagging @lognaturel so she has visibility into this as well.

**Comment by ggalmazor** [comment]
I almost forgot that I created a [PR migrating that project to Gradle](https://github.com/opendatakit/aggregate-components/pull/1). Once migrated to Gradle, just by changing `targetCompatibility` to `1.9` in `build.gradle`, you can produce a JAR that works with Java9 but then it doesn't work with previous versions of Java (don't know why yet).

**Comment by yanokwa** [comment]
I don't love this being in another repo for visibility reasons. Do you think we should move that project here and make it part of the Aggregate? Or find some way to do the upload without it?

**Comment by yanokwa** [comment]
@ggalmazor I bet this is the same issue as https://github.com/opendatakit/briefcase/pull/284. Can you review, and if my bet is correct, please submit a PR.

**Comment by ggalmazor** [comment]
Hi! I've just created a new PR that updates the updater app for the installation process.

It seems like originally we used the jar-in-jar class loader to run this app, but after updating the project to Gradle I didn't see the need for this, as a simple shadowed uberJAR would work. (not using Bouncy Castle on this one).
