### ISSUE TITLE
Migrate to a Gradle task BitRock InstallBuilder project generation

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#115]
The current process for generating Aggregate installers involves lots of manual work and duplicated files, making changing anything hard and prone to errors.

We could leverage a Gradle task to generate an InstallBuilder project from the source code an a set of static assets. We could also remove bulky assets like Google's AppEgine SDK that could be downloaded on-demand.

**Comment by lognaturel** [comment]
A++++ did I understand correctly in Slack that you already have this partially done, @ggalmazor?

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

That's right. I've already prepared a branch with the solution
