### ISSUE TITLE
Reduce size of repo

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#128]
The Aggregate repo is large (~700MB) and that makes it difficult for our devs working in the environments that ODK targets. Large repos also make CI slow. 

Just like we did in https://github.com/opendatakit/docs/pull/72#issuecomment-323911823, I propose we use https://github.com/bozaro/git-lfs-migrate/releases to reduce the size of the repo and store all binary blobs on Git LFS.

To get the largest files in the repo, I used this.
```
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| awk '/^blob/ {print substr($0,6)}' \
| sort --numeric-sort --key=2 \
| cut --complement --characters=13-40 \
| numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```
Then I found all file extensions greater than 84KB (the size of the largest Java file) and that gave me this list: `bin, dll, gwt-log, ico, jar, png, psd, zip`.

So given that, the rough commands that we'll need to use is:

```
mkdir lfs;
git clone --mirror git@github.com:opendatakit/aggregate.git;
java -jar git-lfs-migrate.jar -s aggregate.git -d lfs/aggregate.git -g git@github.com:opendatakit/aggregate.git "*.bin" "*.dll" "*.gwt-log" "*.ico" "*.jar" "*.png" "*.psd" "*.zip";
cd lfs/aggregate.git;
git fsck && git push --mirror --force git@github.com:opendatakit/aggregate.git; 
```

In my tests, this should bring the repo from 700MB to 30MB, which is pretty good.

**Caveats**
* This will require people who have cloned Aggregate to re-clone. But the longer we wait, the more people will have to.
* Github LFS costs the project a little money: https://help.github.com/articles/about-storage-and-bandwidth-usage. But we have a little money.

**Comment by ggalmazor** [comment]
I did some quick checks (after merging #122):
- the current weight of the project is 18 MB without git stuff and 33MB with git history if everything is committed a single commit
- squashing all repo history into one commit with the last point in time with an Eclipse project, and a second commit with the current project weights 151 MB

Do this numbers give us new options? Example: archive history up to f110aa9 in a new repo and reset git history on this one. This would produce a 33MB repo.

**Comment by yanokwa** [comment]
Given that the code base isn't tested and well documented, I think repo history is really important. I definitely would not want to squash it.

I also find the archived repo option is not as elegant as switching to git lfs. That is, we can have the history and the files we want in a single repo.

@lognaturel and @wbrunette Do you have a preference on how we proceed?

**Comment by lognaturel** [comment]
Good to know what the options are. I agree that having history easily accessible through `blame`, etc. would be ideal.

**Comment by wbrunette** [comment]
Having history is useful when understanding how things changed, without it will be hard to answer why something was done. Unfortunately, the answer to why X was done is likely Google App Engine, but it's good to be able to verify it with history.
