### ISSUE TITLE
Adjust IntelliJ setup to help newbies

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#131]
I think the goal of a readme should be to get people up and running quickly. The current IntelliJ documents are really close. Here are improvements I would suggest.

1. It's not clear that the Functional tests module instructions (link is broken!), Aggregate configurations, and Supported database configuration are what I should see first.  Instead of Debugging with Tomcat 8, maybe it should be something like "Getting started with Tomcat 8 and PostgreSQL". Then add that you need PostgreSQL installed. Then after that section, we can put ways people can deviate from that (e.g., database configuration).

1. It's not obvious how to setup and create the odk_db needed to run Aggregate. That information is at https://github.com/opendatakit/aggregate/blob/master/docs/database_configurations.md#database-initialization, but I had trouble finding it. I would add a link on how to setup the DB at the bottom of https://github.com/opendatakit/aggregate/blob/master/docs/intellij_setup.md where people need to see it.

1.  I would also add information now how to set your local IP in security.server.hostname and connect that to your emulator, since that's going to be the common thing that people do.

**Comment by ggalmazor** [comment]
PR #133 introduces the ability to run a development embedded Jetty server instead of deploying to Tomcat. The current instructions for Tomcat would be deprecated by this PR when it's merged.
