### ISSUE TITLE
Run in embedded Jetty with Gradle Task

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#132]
Current instructions for development include the deployment of a WAR to a local Tomcat using IntelliJ Ultimate. The Community version doesn't have the required plugin to do so, forcing developers to deploy the WAR into their Tomcat installation manually.

Gradle has a plugin called [Gretty](https://github.com/akhikhl/gretty) that can run an embedded Jetty or Tomcat server and deploy the WAR into it. We could use this plugin to make the development easier and to enable working with IntelliJ Community edition.

**Comment by yanokwa** [comment]
Closed by #133
