### ISSUE TITLE
Aggregate should be able to be deployed in any path

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#137]
Currently, it only works if deployed in Tomcat's `ROOT` webapp. Otherwise, it gives a "You do not have permission for this action. Error: Invalid request" error upon accessing it.

**Comment by lognaturel** [comment]
I believe that's not the case -- see https://github.com/opendatakit/aggregate/issues/201#issuecomment-367500491

**Comment by ggalmazor** [comment]
True.

I was getting that error due to some session contamination from a prior launch of Aggregate on other path.

Aggregate does support launching on non-root paths :)
