### ISSUE TITLE
Reduce watchdog log spamming

### ISSUE THREAD

**Issue by zwets** [opendatakit/aggregate#140]
Out of box, Aggregate produces 14 lines of log output every 15 minutes. These log entries appear even when nothing out of the ordinary happens, and even when there is no change whatsoever in the state of the application.

My suggestion would be to let the Watchdog report _once_ at INFO level that it is scheduled to do its job every 15 minutes, and then be silent* every time it performs its job as expected. We don't need the application to tell us that it is operating as designed 1344 times a day!

I know that setting `org.opendatakit.aggregate.task.WatchdogWorkerImpl.level=WARNING` in `logging.properties` achieves the same, but I consider that a workaround for what should really be fixed in the implementation.

*) That is, report at FINE level.

**Comment by ggalmazor** [comment]
Hi, @zwets and @jniles! Thanks for contributing to Aggregate with this issue.

I've reviewed the classes that produce these log messages you're complaining about and it feels like some of them are redundant and could be removed but it is helpful to keep some at `DEBUG` level to assist on bug fixing work.

This combined with setting the log level to `INFO` would prevent too verbose log files.

Would you like to make the changes to the code and create a PR?

**Comment by yanokwa** [comment]
Reminds me of the [Everything is OK Alarm](https://www.youtube.com/watch?v=lTzByQTeyJQ) 😂

If you're up for a PR, this would be a nice quick contribution, @zwets!

**Comment by zwets** [comment]
@yanokwa LOL, indeed. Am happy to make a PR, will find some time for it next week.

**Comment by yanokwa** [comment]
To make sure no one takes the issue, write the following, without the quotes in a comment: `@opendatakit-bot claim`

**Comment by lognaturel** [comment]
@zwets We're ramping up for a new release very soon. Would be great to get your PR in or if you don't think you'll be able to get to it in the next week perhaps someone else can do it.

**Comment by zwets** [comment]
@lognaturel Hi Hélène, haven't got around to it, suffering from accumulating amounts of negative spare time. Will bump it on my TODO list, but equally happy if someone else picks it up.
 
Note that the simplest fix (which is superquick and yet _not_ dirty) is to just reduce the log severity of the offending statements from `INFO` to `FINE`. That's a very minor incision, and it is justified: the statements _should_ log below `INFO`.

The other point (having the Watchdog report once at startup that it is running) really is just a nice to have. Assuming that it logs a `WARN` or worse if it does _not_ start, then the "I'm OK" isn't needed. Also, for those who want to be sure, there is always  `org.opendatakit.aggregate.task.WatchdogWorkerImpl.level=FINE`.

**Comment by yanokwa** [comment]
Thanks so much for sending in this PR, @zwets! 

BTW, most of the Aggregate dev team hangs out in http://slack.opendatakit.org in the #aggregate-code channel. If you have a question that needs a real-time answer or just want to hang out with the dev community, join us!
