### ISSUE TITLE
Unknown property warMode 

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/aggregate#150]
When trying to run the `appStartWar` task for the first time I get the following error (from intelliJ or CLI):

> Error:(152, 0) Could not get unknown property 'warMode' for task ':war' of type org.gradle.api.tasks.bundling.War.

I was able to address this by moving `gradle.properties.example` to `gradle.properties`. I'm not sure whether the solution is to add that to the instructions or ...?

**Comment by ggalmazor** [comment]
Yes! We started using that file intensively after some recent PRs and I totally forgot about adding it to the instructions. I'll add something to the `README.md`
