### ISSUE TITLE
Use Java 8 runtime for AppEngine in anticipation of Java 7 runtime deprecation

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/aggregate#184]
As discussed in https://forum.opendatakit.org/t/odk-aggregate-deprecation-of-the-java-7-runtime-environment-on-app-engine-standard/11178, Google will deprecate AppEngine Java 7 runtime support on January 16, 2019.

Instructions for migrating: https://cloud.google.com/appengine/docs/standard/java/migrating-to-java8

It would be good to start by confirming whether anything does still require Java 7 or not. I have a vague memory that something might but I'm not sure what it would be.

**Comment by wbrunette** [comment]
FYI .... The gotcha can come with the "jars" as they all need to be compiled for the same JDK as the compiled code. The compiler should point out flaws in the code base that it is compiling.
