### ISSUE TITLE
Unable to import as Gradle Project

### ISSUE THREAD

**Issue by jackengine** [opendatakit/aggregate#190]
Software and hardware versions 
Windows, Aggregate v1.4.5, Java v8

Problem description
Fresh import in Intellij Idea produces error.
`Process 'command 'cmd'' finished with non-zero exit value 128`

Steps to reproduce the problem
Fresh import in Intellij Idea produces error. With above versions and latest Community IDE

Things you tried, stack traces, related issues, suggestions on how to fix it...
Tried changing gradle version 3.x and latest

**Comment by ggalmazor** [comment]
Hi @jackengine! I'm sorry that you're having trouble setting up your dev environment. I'll try to help here but, if you want, I'm also on our [#aggregate-code Slack channel](https://opendatakit.slack.com/messages/C4146P8TA)

Just to be sure, you mentioned that you're trying Aggregate v.1.4.5 but this version is several months old. The latest version is v.1.4.15 and I'm assuming that it's just a typo on your issue description, but, could you confirm this, please?

**Comment by jackengine** [comment]
Hi @ggalmazor It is aggregate v1.4.15

**Comment by yanokwa** [comment]
And what version of Windows are you running?

**Comment by jackengine** [comment]
Hi @yanokwa Windows 8.1

**Comment by ggalmazor** [comment]
Hi @jackengine! I've tried to reproduce your problem (fresh installation of IntelliJ Community and fresh clone of the code) and it's working for me. 

Other users have had problems with git-lfs, which you need to have installed **before** cloning the repo. Can you confirm this, please? If you need to install git-lfs, you can follow [these instructions](https://git-lfs.github.com/)

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by jackengine** [comment]
Nope, this did not solved. I installed and cloned again. Not worked. Any special command I need to execute **after** cloning repo?

**Comment by ggalmazor** [comment]
Hi @jackengine! Honestly, I don't know what's going on.

Just to be sure, I've tried to reproduce the error on a Windows 10 machine with a clean installation of IntelliJ Community edition. I've created the project with the "Checkout from version control" option. Once the project is imported, I can set everything up and get Gradle to work and compile the project. I've recorded a video doing this: https://www.youtube.com/watch?v=aex2HUL4X5I

I'm guessing that there is something wrong with your Windows environment...

**Comment by yanokwa** [comment]
Agreed with @ggalmazor. There is something wrong with your env, @jackengine. 

In the repo folder, run the following commands and report the results.
* `./gradlew --version`
* `gradle --version`
* `cmd`

**Comment by jackengine** [comment]
You guys were right. It was problem with environment and permission. Thanks..

**Comment by ggalmazor** [comment]
Hi @jackengine! I'm glad that you solved your problem. I think others could benefit from your experience in the future if we document your problem just a little bit. Is there something you could comment on the environment settings or permissions you had to fix, etc.?

This way, someone with a problem like yours in the future could benefit from your solution.
