### ISSUE TITLE
User can "publish" submissions/forms to servers without choosing any fields,

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#209]
#### Software and hardware versions 
Aggregate v1.4.x, Java v1.8.x, ...

#### Problem description
User is able to publish data to servers without choosing any fields. I think that some information about required fields should be added or publish button may be disabled or error message should inform user what went wrong and give a chance to correct users choices.

#### Steps to reproduce the problem
Click on publish button next to submission or form. On displayed publish window choose one of servers JSON, REDCap or Ohmage JSON, leave all fields empty and click on publish button. You probably will have an impression that it succeeded. 

#### Expected behavior
It would be user-friendly to inform him what fields to fill/ disable publish button when parameters are not chosen/ some dialog message. We might need discussion here. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by ggalmazor** [comment]
Closed by #416
