### ISSUE TITLE
Too late error message when not choosing name workbook name when publishing to Google Spreadsheet.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#210]
#### Software and hardware versions 
Aggregate v1.4.x, Java v1.8.x, ...

#### Problem description
Too late error message when not choosing name workbook name when publishing to Google Spreadsheet.

#### Steps to reproduce the problem
Click on publish button next to submission or form. Choose to publish to Google Spreadsheet. Leave Workbook name field empty. Click on publish button. Dialog message asking you for email will appear. Input email address, confirm email address and finally, you will see error message informing you that "Spreadsheet name must be supplied."

#### Expected behavior
Error message shows which is good but it should display earlier or give users the chance to correct his action and input workbook name again or publish button may be disabled when user doesn't choose a workbook name.

#### Other information 
Screenshot of error message attached.
![screenshot_error spreadsheet](https://user-images.githubusercontent.com/33342488/37201742-ca42c8d0-2388-11e8-8c41-0bcc64bfde38.png)

**Comment by ggalmazor** [comment]
Closed by #416
