### ISSUE TITLE
Unable to open page aggregateurl/users/list

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#213]
#### Software and hardware versions 
GAE and Tomcat, Aggregate v1.5.x, Java vx.x.x, ...

#### Problem description
Unable to open pages mentioned at: https://docs.opendatakit.org/aggregate-upgrade/
Aggregate 1.4.12  point 7

#### Steps to reproduce the problem
Try to open page: youraggregateurl/users/list

#### Expected behavior
I am able to open it with GAE instance od aggregate 1.4.13 

#### Other information 
Screenshot of my result: (I am logged in as super-user)
![screenshot from 2018-03-15 12-55-48](https://user-images.githubusercontent.com/33342488/37461903-5450a832-2850-11e8-9e2a-f6af6d31d8c4.png)

Screenshot of the result on 1.4.13:
![screenshot_userslist](https://user-images.githubusercontent.com/33342488/37461952-79bc805a-2850-11e8-8743-ed2948290cb4.png)

**Comment by ggalmazor** [comment]
Diff-ing `war-base/WEB-INF/web.xml` between `v1.4.13_Production` and `v1.4.14_Production` shows that this URL was removed on the 1.4.14 release.

You can see the changes between those release with the command: 

```
git diff v1.4.13_Production..v1.4.14_Production war-base/WEB-INF/web.xml
```
(you need to be on a branch where war-base/WEB-INF/web.xml exists)

@yanokwa, @lognaturel, do you remember why? Do we need to recover this URL?

**Comment by kkrawczyk123** [comment]
I think that this issue is outdated so I am closing it.

**Comment by yanokwa** [comment]
https://github.com/opendatakit/aggregate/commit/542f3a4e18c3bd7f992ef635ce20f92efc203c88#diff-960a449da9d58c5be9c6a1d2aff37f81 suggests that it was used by ODK Tables (ODK 2) which is no longer in Aggregate. No need to recover the URL.

**Comment by ggalmazor** [comment]
Thanks, @yanokwa!
