### ISSUE TITLE
ODK Aggregate folder has grown 100 MB

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#227]
Running the Aggregate installer for GAE produces an ODK Aggregate folder that is 100 MB larger. The difference seems to be files added from the appengine-java-sdk.

<img width="1116" alt="file-diff" src="https://user-images.githubusercontent.com/32369/37547236-9f261b70-292d-11e8-8fec-16b138ef12ed.png">

**Comment by ggalmazor** [comment]
I'll remove those folders from the diff: demos, jetty*, src

They get the SDK from 231M to 167M, is that right?

**Comment by ggalmazor** [comment]
Removing the docs gets us to 145M
