### ISSUE TITLE
Review missing libraries in Aggregate.war

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#229]
Aggregate 1.5.0 includes the classes folder in the war and drops a lot of libraries in the MySQL (and probably PostgreSQL install). I'm filling this issue to get a quick review of this behavior.

<img width="1118" alt="screen shot 2018-03-16 at 16 01 41" src="https://user-images.githubusercontent.com/32369/37548170-5916063a-2933-11e8-8448-aa0db55f81cd.png">

**Comment by ggalmazor** [comment]
Here's my review of the differences between 1.4.15 and 1.5.0:

| Artifact                                                | Status  | Reason                            |
| ------------------------------------------------------- | ------- | --------------------------------- |
| `adal4j-1.2.0.jar`                                      | removed | Wrong transitive                  |
| `aggregate-src-latest.jar`                              | removed | Replaced by `WEB-INF/classes`     |
| `bcpkix-jdk15on-1.56.jar`                               | removed | Wrong transitive                  |
| `bcprov-jdk15on-1.56.jar`                               | removed | Wrong transitive                  |
| `commons-codec-1.10.jar`                                | removed | Wrong transitive                  |
| `commons-codec-1.9.jar`                                 | new     | Fixed transitive                  |
| `commons-collections4-4.1.jar`                          | removed | Wrong transitive                  |
| `commons-io-2.2.jar`                                    | new     | Fixed transitive                  |
| `commons-io-2.5.jar`                                    | removed | Wrong transitive                  |
| `commons-logging-1.2.jar`                               | removed | Logging migration to SLF4J        |
| `google-api-services-sqladmin-v1beta4-rev25-1.22.0.jar` | removed | Wrong transitive                  |
| `jai-imageio-core-1.3.0.jar`                            | removed | Wrong transitive                  |
| `jaxb-api-2.2.1.jar`                                    | new     | Fixed transitive                  |
| `jaxb-api-2.2.jar`                                      | removed | Wrong transitive                  |
| `jcip-annotations-1.0-1.jar`                            | removed | Wrong transitive                  |
| `jcl-over-slf4j-1.7.25.jar`                             | new     | Logging migration to SLF4J        |
| `json-smart-1.3.1.jar`                                  | removed | Wrong transitive                  |
| `jsr305-1.3.9.jar`                                      | new     | Fixed transitive                  |
| `jsr305-3.0.1.jar`                                      | removed | Wrong transitive                  |
| `lang-tag-1.4.3.jar`                                    | removed | Wrong transitive                  |
| `log4j-over-slf4j-1.7.25.jar`                           | new     | Logging migration to SLF4J        |
| `mail-1.4.7.jar`                                        | removed | Wrong transitive                  |
| `mysql-connector-java-5.1.44.jar`                       | new     | Update JDBC drivers               |
| `mysql-socket-factory-1.0.2.jar`                        | removed | Replaced by the Java connector    |
| `mysql-socket-factory-core-1.0.2.jar`                   | removed | Replaced by the Java connector    |
| `nimbus-jose-jwt-4.39.2.jar`                            | removed | Wrong transitive                  |
| `oauth2-oidc-sdk-5.18.1.jar`                            | removed | Wrong transitive                  |
| `opendatakit-javarosa-2.3.0.jar`                        | removed | Replaced with version 2.6.0       |
| `opendatakit-javarosa-2.6.0.jar`                        | new     | Update JavaRosa                   |
| `postgresql-42.1.4.jre7.jar`                            | new     | Update JDBC drivers               |
| `postgresql-9.4.1211.jre7.jar`                          | removed | Replaced with version 42.1.4.jre7 |
| `servlet-api-2.5.jar`                                   | new     |                                   |
| `slf4j-api-1.7.22.jar`                                  | removed | Logging migration to SLF4J        |
| `slf4j-api-1.7.25.jar`                                  | new     | Logging migration to SLF4J        |
| `slf4j-jcl-1.7.22.jar`                                  | removed | Logging migration to SLF4J        |
| `slf4j-jdk14-1.7.25.jar`                                | new     | Logging migration to SLF4J        |

- Those marked as **Wrong transitive** are removed artifacts that were being manually added to the WAR in v.1.4.15 and aren't being used anymore or have the wrong version
- Those marked as **Fixed transitive** are new artifacts that fix the version of a corresponding **Wrong transitive** artifact

It's curious that the correct version of some transitive dependencies is, in fact, smaller than the ones we were shipping on v.1.4.15...

I have doubts about the `servlet-api-2.5.jar`. I bet that both Tomcat and AppEngine add that to the classpath and we don't need that in our WAR...

**Comment by yanokwa** [comment]
Thanks for this great summary!
