### ISSUE TITLE
Running behind proxy

### ISSUE THREAD

**Issue by sadiqkhoja** [opendatakit/aggregate#237]
I am running tomcat on port 8080 behind nginx with SSL (port = 443). Most of the functions are working but /formList has http instead of https in path of forms. 

Here are my security.property:

```
security.server.deviceAuthentication=digest
security.server.secureChannelType=ANY_CHANNEL
security.server.channelType=ANY_CHANNEL
security.server.hostname=
security.server.port=80
security.server.securePort=8443
wink.handlersFactoryClass=org.opendatakit.aggregate.odktables.impl.api.wink.AppEngineHandlersFactory
```

changing channelType to REQUIRES_SECURE_CHANNEL starts redirecting ODK to port 8443 where nobody is listening.

Can we have protocol read from X_Forwarded_Proto or X-Url-Scheme for proxy setup?

ODK Aggregate version:  1.4.15

**Comment by lognaturel** [comment]
@ggalmazor I think this is similar to recent conversations you've been in on the forum about deployments behind a load balancer. Would be great for a solution to address both.

**Comment by yanokwa** [comment]
I believe this has been fixed by https://github.com/opendatakit/aggregate/pull/254.

@sadiqkhoja are you able to test the upcoming beta to help verify this works for you?

**Comment by sadiqkhoja** [comment]
I ll verify it over the weekend.

**Comment by ggalmazor** [comment]
Hi @sadiqkhoja! 

I wanted to give you a heads up about some stuff that's been going on for the last months:
- We're releasing Aggregate v2.0 during the next days and we've included a CloudConfig stack that could be easily modified to run behind a load balancer or proxy.
- We've also fixed some standing issues with the way URL redirects are handled with #393.

Now it should be easier to have custom infrastructures like the one you're using.

I'm closing this issue now, but feel free to reopen it if you want to discuss anything ;)

**Comment by sadiqkhoja** [comment]
Thanks
