### ISSUE TITLE
Add binaries to releases

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#238]
Aggregate binaries are needed for users to upgrade incrementally. We need to grab them from AWS and add them to the Github releases.

**Comment by ggalmazor** [comment]
Starting from v2.0, we will be releasing the WAR packages along with the rest of artefacts we're currently releasing (VM & installers). Does that solve this issue?

**Comment by yanokwa** [comment]
Nope! This issue was for me to add the old installers to the GH releases. I did that months ago, so this issue can be closed.
