### ISSUE TITLE
Aggregate adds a comment with upload time to forms

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/aggregate#242]
#### Problem description
Aggregate adds a comment like:

`<!-- ODK Aggregate upload time: 2018-05-09T13:18:46.481+0000 on https://gorczykowski-aggregate.appspot.com -->`

to forms. It causes a problem on the Collect's side because when we check for form updates we compare md5 hashes.

So if a user removes a form and add exactly the same form again in the Collect it's visible as an updated version.

It's not a big problem since that case is not really common I belive but do we really need that comment?

**Comment by ggalmazor** [comment]
I like the idea of removing it. Ideally, I think we should even save the original blank form as a blob and return it when the user wants to download it.

**Comment by yanokwa** [comment]
I'm not sure why this was added, but it's been there for a while. It's not really hurting anything and what if someone uses that comment downstream?

**Comment by yanokwa** [comment]
Discussed with @ggalmazor and @lognaturel. The consensus is that this doesn't affect a lot of people and could break downstream tools, so we aren't going to fix.
