### ISSUE TITLE
Installation of ODK Aggregate fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by sachinoze** [opendatakit/aggregate#249]
#### Software and hardware versions 
ODK Aggregate version 1.4.15
Ubuntu - 16.04
Apache Tomcat - 9.0.8
MySQL - 5.7.22
MySQL Connector Java - 8.0.11
Java - 1.8.0_171

#### Problem description
Installation fails with following error

WARNING: Failure: _granted_authority_hierarchy exception: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [SHOW COLUMNS FROM vidhi_odk._granted_authority_hierarchy]; Cannot determine value type from string 'NO'; nested exception is java.sql.SQLDataException: Cannot determine value type from string 'NO'

#### Steps to reproduce the problem
Install ODK Aggregate on Ubuntu

#### Expected behavior
Installation is successful

#### Other information 
The exception is caused due to line: 233 in file aggregate/src/main/java/org/opendatakit/common/persistence/engine/mysql/DatastoreImpl.java

this.isNullable = rs.getBoolean(IDX_IS_NULLABLE);

tries to read a boolean value whereas the record set returned by MySQL is as follows
_URI | varchar(80) | NO | MUL | NULL 
so value NO cannot be converted to boolean by rs.getBoolean method

Code can be easily updated to do string comparison with "NO", but I am not sure what is the value returned by other data sources like PostgreSQL, MS SQL, etc

[catalina.txt](https://github.com/opendatakit/aggregate/files/2041864/catalina.txt)

**Comment by ggalmazor** [comment]
Hi @sachinoze! Thanks for reporting this issue :)

It's true that the column type of the `IS_NULLABLE` column of a `SHOW COLUMNS ...` is `VARCHAR(3)`, which is not boolean, but in my setup, the connector is taking care of that. I'm using the connector version defined in the Gradle build file, which is 5.1.44.

I've debugged the connector and I can see that the required data type coercion is done in `com.mysql.jdbc.ResultSetImpl` in the method `getBoolean(int columnIndex)` (line 1517). There, the string value gets parsed into a boolean, unless the connection has been defined in `pedantic` mode (funny name).

Are you using the connection version 8.0.11 for some reason? An easy solution would be to downgrade that to 5.1.44, which is the one the code supports.

Let me know if this helps ;)

**Comment by ggalmazor** [comment]
Hi, @sachinoze! I wanted to check on you regarding the issue you opened some weeks ago. Did you have a chance to review my comment?

**Comment by sachinoze** [comment]
Hi @ggalmazor 
Thanks for the help. Using version 5.1.44 did help.
Apologies for the late reply.

Cheers

**Comment by ggalmazor** [comment]
Thanks for getting back with an update, @sachinoze! I'm glad it is working for you now :)
