### ISSUE TITLE
Don't crash when unknown function or attribute is used

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/aggregate#252]
When a user tries to upload a form that includes an unknown function or attribute, the form upload is refused. However, functions and most attributes aren't evaluated or used by Aggregate in any way so this check is not necessary. Clients may differ in which functions and attributes they support and Aggregate shouldn't limit usage.

Currently the error message is `Error: Problem with JavaRosa Parsing Form: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: Javarosa failed to construct a FormDef. Is this an XForm definition?`

Ideally those kinds of unknown form elements would result in warnings only. 

Note that it's really important that Aggregate know about newly-introduced data types because that's how it builds its data store so errors triggered by an unknown data type should block upload.

CC @yanokwa @ggalmazor

**Comment by lognaturel** [comment]
That is fantastic news!

I initially was trying [randomize.xml.txt](https://github.com/opendatakit/aggregate/files/2099506/randomize.xml.txt) which does fail. I should really have included this in the initial issue and also tried other forms before reaching a broad conclusion.

I tried different variations on @ggalmazor's `simple` form and the smallest change I can find that makes it fail is including a function in a value for `nodeset`. This triggers a `XPathTypeMismatchException` which is more severe. I think it's ok that it doesn't upload. The error message isn't all that helpful but changes this significant to allowable syntax are rare. The upgrade to JR 2.10 will fix this specific problem.

**Comment by ggalmazor** [comment]
Great new. Then I guess we don't need to do anything :)

**Comment by lognaturel** [comment]
Best kind of issue! 😉

Will be more careful before filing next time.
