### ISSUE TITLE
Add conf param to enforce HTTPS link generation

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#253]
#### Problem

As discussed on [this forum post](https://forum.opendatakit.org/t/installing-odk-aggregate-behind-an-ssl-load-balancer-issues/13029/3?u=ggalmazor), and others, some users are trying to add an SSL/TLS layer using a load balancer, instead of configuring Tomcat. This setup is very convenient, especially when dealing with cloud providers like Amazon that make the whole process of adding certificates and setting everything up really easy.

From the point of view of any client trying to speak with the Aggregate server, all communication is secure (HTTPS), but from the point of view of the Aggregate server, everything is done in an open channel (HTTP). Overall, this can be a secure setup, provided that the network has correct security policies in place (this is another whole topic), and it's quite convenient.

Aggregate can be configured to work either in a secure channel (HTTPS) or an open channel (HTTP) and this affects the URLs it builds to let clients know where the form definition files and attached media files can be downloaded from. 

In this scenario, Aggregate should be configured to work on an open channel (HTTP) and this will produce URLs with the HTTP schema which will be rejected by the load balancer.

Some load balancers can be configured to redirect HTTP requests to HTTPS and users can also deploy proxies in their networks to achieve that, but that makes the process of deployment more complex.

#### Proposed solution

Aggregate could have a new configuration parameter to decide whether to use HTTPS or HTTP schema in the links it produces, regardless of the networking configuration.

This would let users configure Aggregate to work on an open channel (HTTP) but generate links that use the HTTPS schema.

**Comment by lognaturel** [comment]
The proposed solution sounds really good to me, @ggalmazor.
