### ISSUE TITLE
Link to exported .csv files displayed incorrectly. 

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#259]
#### Software and hardware versions 
Aggregate v1.6.x, Java v1.8.x, Tomcat and GAE aggregates

#### Problem description
Link to downloading exported csv file is displayed like:
![screenshot from 2018-06-21 12-08-39](https://user-images.githubusercontent.com/33342488/41713146-9e039428-754c-11e8-9004-ca72baf2a4bd.png)

#### Steps to reproduce the problem
1. Export submissions to csv file

#### Expected behavior
In aggregate 1.5 link to downloading is displayed:
![screenshot from 2018-06-21 12-15-02](https://user-images.githubusercontent.com/33342488/41713220-c6850dc8-754c-11e8-8c48-479220c4de50.png)

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
