### ISSUE TITLE
Rollback button and installation window are cut off when installing GAE on Ubuntu.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#264]
#### Software and hardware versions 
Linux, Aggregate v1.6.x, Java vx.x.x, ...

#### Problem description
Rollback button and installation window are cut off when installing GAE on Ubuntu.
Screenshot attached:
![screenshot from 2018-06-22 11-30-10](https://user-images.githubusercontent.com/33342488/41848182-e52e50c6-787c-11e8-9ebd-26ed370daf49.png)

#### Steps to reproduce the problem
Install GAE on Ubuntu. 

#### Expected behavior
The Rollback button should not be cut off.

#### Other information 
The problem doesn't occur on Windows and MacOS.

**Comment by ggalmazor** [comment]
In Debian Linux with Gnome desktop (like Ubuntu) I can't reproduce:

![image](https://user-images.githubusercontent.com/205913/41957067-ff45a94a-79e5-11e8-95b6-57949a0f42e5.png)

I'll try with Ubuntu in a VM. What version of Ubuntu was? 18 or 16?

**Comment by kkrawczyk123** [comment]
I am using Ubuntu 16.04 and Marzena is using Ubuntu 14 and we both had the same issue.
