### ISSUE TITLE
Preview of audio files is not available, downloading is forced.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#280]
#### Software and hardware versions 
Aggregate v1.6.x,GAE and tomcat instances.

#### Problem description
Preview of audio files is not available, downloading is forced.

#### Steps to reproduce the problem
1. Send to aggregate submission with the audio file and video file.
Try to preview audio file - you are forced to downloading it.
Try to preview audio file - you are able to preview. 

#### Expected behavior
Preview of both file types should be available.

**Comment by ggalmazor** [comment]
I've tried this with 1.5.0 and the behavior is the same. The browser decides whether it can reproduce and when it can't, it downloads the file to the host.

**Comment by lognaturel** [comment]
Let me make sure I understand -- this just uses browser preview and if none is available goes to download? If that's the case then I think this is fine and we can close.

**Comment by ggalmazor** [comment]
That's my understanding from the tests @kkrawczyk123 and I made when dealing with the last release. We decided to create this issue to document it.

**Comment by ggalmazor** [comment]
Closing, as per discussion.
