### ISSUE TITLE
Deprecate publishers we can't verify as functional

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#290]
I'd like to deprecate the following publishers:

* RedCap Server because it's a closed community where we can't even ask if the publisher is used. Also, according to https://forum.opendatakit.org/t/redcap-to-odk/1477/30 I'm pretty sure it doesn't work.
* Ohmage JSON server because according to https://github.com/opendatakit/opendatakit/wiki/Aggregate-Publishers-Implementation-Details#known-issues it has no verified accepting servers. We shouldn't ship things we can't verify as working. I'd be surprised if anyone is using it.

My proposed approach here is pretty direct.
* In the next release, ~~replace Z-ALPHA in the type and~~ prepend (Deprecated). This will allow users who have those publishers to see their status in the publish status page.
* ~~Remove the choice from the drop down list so users cannot create new publishers.~~
* Update the docs to reflect this change.

Note that we want people to be able to delete publishers even after we remove the choice.

I could be convinced that we stagger this over two or three releases if everyone thinks my direct approach is unkind to users. But you know we can point out this deprecation in the beta and people don't have to upgrade.

**Comment by aurdipas** [comment]
I agree on your approach. +1

**Comment by smoyth** [comment]
Works for me. A message on the forum in advance might also be a nice courtesy.
