### ISSUE TITLE
Error reading odk-tomcatutil gwt-google-maps gwt-visualization odk-httpcliente-gae en libs folder; error in opening zip file

### ISSUE THREAD

**Issue by gouky10** [opendatakit/aggregate#292]
#### Software and hardware versions 
Ubuntu 17.10
Linux 4.13.0-46-generic
IntelliJ IDEA 2018.1.6 (Community Edition)
Build #IC-181.5540.7, built on July 11, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

#### Problem description
I followed the README.md file instructions, but when I try to RUN I get dependency problems:

`10:32:19 AM: Executing task 'appStartWar'...

:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:generateBuildConfig UP-TO-DATE
:compileBuildConfig UP-TO-DATE
error: error reading /home/gouky10/development/aggregate/libs/odk-tomcatutil-1.0.1.jar; error in opening zip file
error: error reading /home/gouky10/development/aggregate/libs/gwt-google-maps-v3-1.0.1.jar; error in opening zip file
error: error reading /home/gouky10/development/aggregate/libs/gwt-visualization-1.1.2.jar; error in opening zip file
error: error reading /home/gouky10/development/aggregate/libs/odk-httpclient-gae-4.5.2-1.jar; error in opening zip file
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
Compilation failed; see the compiler error output for details.
10:32:21 AM: Task execution finished 'appStartWar'.
`

#### Steps to reproduce the problem
I follow the instructions in README.md file

1. Getting the code section
2. Setting up the database with Local PostgreSQL server
3. Running the project ---> Import ----> Configure ---> Run

#### Expected behavior
War file create to deploy a tomcat server with ODK Aggregate

#### Other information 
Hello Its my first time that I try to install ODK Aggregate I think its a gradle or Intelli J missing configuration.
My gradle configuration in Intelli J is:
![captura de pantalla de 2018-07-24 10-53-41](https://user-images.githubusercontent.com/3301382/43150581-df7fc9ce-8f2f-11e8-9f57-e6fa5bef1a80.png)

I looked for similar issues but whitout success. Please help me.

**Comment by yanokwa** [comment]
@gouky10 Did you install Git LFS (as described in Step 2 at https://github.com/opendatakit/aggregate#getting-the-code)

**Comment by behindtheshadow** [comment]
I got the same error ... :(

**Comment by ggalmazor** [comment]
Hi, @behindtheshadow!

Could you run this where you have cloned the Aggregate repo and copy the results here, please? `git lfs env`

**Comment by ggalmazor** [comment]
Hi @behindtheshadow! You wanted to follow up your initial issue. Did you have a chance to run the command from my last comment?

**Comment by ggalmazor** [comment]
Closing this issue since it's related to an issue while setting up the development environment.
