### ISSUE TITLE
Add quick primer on encrypted forms to dev docs

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/aggregate#294]
It's easy to forget exactly what info is sent with the encrypted blob and what Aggregate does with it. 

Perhaps https://opendatakit.github.io/xforms-spec/#encryption should also include the submission format.

From @ggalmazor in Slack:

> 1. The public key is attached to the blank form and it is uploaded to Aggregate
>  - Aggregate sees that this is an encrypted form and tricks itself into thinking that the blank form has only three fields: base64EncryptedKey, base64EncryptedElementSignature, and encryptedXmlFile
>  - Here's where the wrong size for those fields happens (<1.5.0 sets that to 2048, 1.6.0 sets that to the default 255)
> 2. Collect pulls the blank form
> 3. The user fills a form and finalizes it
> 4. Collect generates a symmetric key pair (I ignore if it's based on the form's public key or not, but it doesn't matter at this point)
> 5. Collect encrypts the submission into a `submission.xml.enc` file and builds a `submission.xml` file including only three fields:
>  - base64EncryptedKey contains the symmetric key pair encrypted with the form's public key
>  - base64EncryptedElementSignature contains a cryptographic signature of the contents of the submission (using the form's public key again)
>  -  encryptedXmlFile contains the encrypted submission filename 
> 6. Collect sends both files to Aggregate
> 7. Aggregate decomposes the `submission.xml` file and stores the values in the database
>  - It reads 345 chars from base64EncryptedKey but the database truncates that to 255
>  - Same with the signature field
> 8. The user pulls the form with Briefcase
> 9. Sets the export (private key and all) and tries to export it
>  - Briefcase needs to decrypt the symmetric key pair using the private key, but since it was truncated by Aggregate, it's no longer usable
>  - The symmetric key would then be used to decrypt the actual contents of the submission
>  - The signature would also fail decryption for the same reasons. The signature is used to validate that the decrypted contents match the ones the user sent in the first place (they haven't been tampered with)

**Comment by lognaturel** [comment]
I believe that https://opendatakit.github.io/xforms-spec/encryption now has sufficient information. @ggalmazor can you please see if you agree and then close?

**Comment by ggalmazor** [comment]
The docs about encryption in the xforms spec are super complete now. Closing this.
