### ISSUE TITLE
Docker file creation issues

### ISSUE THREAD

**Issue by poVoq** [opendatakit/aggregate#313]
I am trying to follow this tutorial for the new docker option, but the setup seems very strange from a typical dockerfile setup point of view (I think, not an expert on Docker):
https://github.com/opendatakit/aggregate/blob/master/docs/build-and-run-a-docker-image.md

First of all as described here: https://hub.docker.com/_/postgres/
The easiest way to get a database running inside the PostgreSQL container is by giving it ENV variables during startup time. Furthermore to make the data persistent "/var/lib/postgresql/data" should point to a named volume.

But the next step is even stranger, instead of running the dockerfile directly it seems to first want to compile the java .war on the host system, right? Is there any specific reason for this? Usually a Docker host-system is a slim server that does not include Java or other such runtimes.
I believe that typically such compilation steps are done inside the container after creation via the dockerfile. This way things are cleanly separated and the docker container needs to contain java anyways.

Sorry if this doesn't make sense, but I am kind of surprised by this setup as all other docker images I am created so far work more like I described.

**Comment by poVoq** [comment]
> I'm a little confused by this comment. Maybe you can give more context.
> 
> We want to provide an image that just comes with Tomcat 8 and Aggregate already installed. PostgreSQL should be running outside the image we provide.

I was referring to how it is explained in the linked tutorial, which explains how to create this external Postgres image. The explanation there is to create the image and then enter it and create a database manually, which in the case of the official Postgres Dockerimage just doesn't make sense. In addition the data isn't persistant without the named volume, so when recreating or updating the Postgres container all data from Aggregate would be lost.

> The rationale here is that the Aggregate image should only contain runtime binaries and that we want to reuse current tasks and tools defined in the project.
> 
> I know that nowadays you can use a temporary container to compile your project, take the output artifacts and then throw it away, but I don't see any advantage on doing this when the host machine has to have a working development environment in order to build the Docker image. At this moment it's much easier to reuse existing tasks and tools and copy files to the image.

Ok I get the point of wanting to keep the final image small and clean. Once there are official binary releases on Dockerhub, I guess I could just go that way. But as far as I know, there is usually no need to have a working development environment to build images for Docker as they usually include a script to set up everything inside the container, so that there are no external dependencies or any setup process necessary for building the image on a random machine.

**Comment by ggalmazor** [comment]
> I was referring to how it is explained in the linked tutorial, which explains how to create this external Postgres image. The explanation there is to create the image and then enter it

I'm sorry but the instructions don't tell any of that. Now I'm concerned that the instructions are not clear enough. There's no step involving a PostgreSQL Docker image...

> But as far as I know, there is usually no need to have a working development environment to build images for Docker as they usually include a script to set up everything inside the container

I'd really want to learn to make Docker images better. Could you link some examples, please?

**Comment by poVoq** [comment]
Ah :) Ok that was me overthinking it. But starting a separate docker image for postgres is really easy and recommended in a docker setup.

Regarding at better docker image... I quite like how these are setup:
https://github.com/QuantumObject/docker-ushahidi-platform-client
https://github.com/QuantumObject/docker-ushahidi-platform

But after starting today to compile Aggregate, and Ubuntu 16.04 trying to pull in almost a gigybyte of dependencies for it (boy is Java a mess :-1:  ), I abandoned that plan and can understand why you don't want to do that in the container directly...
