### ISSUE TITLE
If multiple files are included in media block for encrypted form, only the first file is kept

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/aggregate#319]
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v1.6.1

#### Problem description
If an encrypted submission with media is made to Aggregate with the following format:
```xml
<media>
<file>blah1.jpg</file>
<file>blah2.jpg</file>
</media>
```

as opposed to 

```xml
<media>
<file>blah1.jpg</file>
</media>

<media>
<file>blah2.jpg</file>
</media>
```

Only the first file is included when decrypting on Briefcase.

#### Steps to reproduce the problem
1. Generate a submission with a media block with multiple files
1. Submit it to Aggregate
1. Pull it from Briefcase
1. Export from Briefcase, see that only the first media file is exported

Note: Collect does not generate such submissions so it would have to be edited on the Collect data store, submitted via curl or something like that.

#### Expected behavior
All media files are included in the export.

#### Other information 
I think the first step would be to see what the submission that gets to Briefcase looks like. That will help narrow down at what level the problem is happening.

**Comment by ggalmazor** [comment]
Closing, since there's no apparent fix or workaround for this.
