### ISSUE TITLE
Leading zeros lost from `version` when listing blank forms

### ISSUE THREAD

**Issue by cooperka** [opendatakit/aggregate#327]
Re-filing https://github.com/opendatakit/collect/issues/2296 under this repo.

#### Software and hardware versions

Aggregate v1.6.1

#### Problem description

Leading zeros are lost from version numbers when listing blank forms from the Aggregate API. For example, version `0001` is transmitted as simply `1`.

#### Steps to reproduce the problem

1. Visit the [sandbox](https://sandbox.aggregate.opendatakit.org/Aggregate.html#management/forms///)
1. Upload example [multi-warning.xml](https://github.com/opendatakit/aggregate/files/2480861/multi-warning.xml.txt)
1. Retrieve the list of blank forms (e.g. via the Collect app)

The response sent back from the server for the Multi Warning form is:

```xml
<xform>
  <formID>multi warning</formID>
  <name>Multi Warning</name>
  <majorMinorVersion>1</majorMinorVersion>
  <version>1</version>
  <hash>md5:c1983e6a874af5cb49b4e484bfadb92d</hash>
  <downloadUrl>https://sandbox.aggregate.opendatakit.org/formXml?formId=multi+warning</downloadUrl>
</xform>
```

Whereas e.g. `<version>500001</version>` is correct when the leading character is non-zero.

#### Expected behavior

Leading zeros should not be lost.

**Comment by ggalmazor** [comment]
Thanks for reporting the issue, @cooperka!

I know that Aggregate converts the version to a number to decide if an incoming form is newer than an already existing one.

What you report looks like Aggregate is storing the numeric representation instead of storing the literal version number coming on the blank form.

There are some things that come to mind:
- Can we store the literal version number on the database?
- Or do we need to add a field to the database to store both? << This could be problematic.

**Comment by cooperka** [comment]
Thanks @ggalmazor. In my opinion, not having delved much into the documentation, it seems like we should either treat the version as a number or a string, and only store it once.

A. If it's a number, and we disallow any letters, stripping the zeros seems fair, but it should be documented that the version is simply a number and nothing more
B. If it's a string, and we allow letters, we should never convert, and instead sort alphanumerically ([this algorithm](https://stackoverflow.com/a/104709/763231), for example)

Requiring the version to be numeric but also allowing leading zeros seems like a complexity not worth supporting to me.

**Comment by ggalmazor** [comment]
From what I gather looking to Aggregate's code, in `XFormParameters` the version string is parsed into a `Long` and then it's used to compare different instances of `XFormParameters` (to know if an instance is greater, equal, or less than another instance).

We should check what the specs say about this field.

**Comment by ggalmazor** [comment]
After thinking about this, and discussing it with @yanokwa and @lognaturel, we've convened that an intervention to change how Aggregate deals with versions would be too risky at this moment.

For the moment, we've reviewed all the documentation available in search for spots where language should be changed and/or information should be added.
- https://github.com/XLSForm/xlsform.github.io/issues/24#issuecomment-433065208
- https://github.com/opendatakit/docs/pull/903
