### ISSUE TITLE
Version information makes it difficult to download form XML

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#330]
#### Software and hardware versions 
1.7.0-beta.0

#### Problem description
If you have a long list of forms, the version number overlaps so you can't click on the form to download it. 

<img width="960" alt="screen shot 2018-10-18 at 21 44 53" src="https://user-images.githubusercontent.com/32369/47198078-1257f000-d31f-11e8-9007-464459aab97b.png">

#### Potential solution
Maybe we move the version to next to the Site Admin tab?
<img width="726" alt="screen shot 2018-10-18 at 21 47 51" src="https://user-images.githubusercontent.com/32369/47198186-b04bba80-d31f-11e8-8c99-fb5f445fecb8.png">
And since this is more visible, maybe we only show the version number when there is no update available (drop the "You're up to date!").

Alternatively, can we add some whitespace to the end of the form listing? The site preferences seems to do something like that.

**Comment by yanokwa** [comment]
For bonus points, we can add the update link to the Version Information section :)

**Comment by ggalmazor** [comment]
Ha! I had the solution *before* you created this issue. Is that another level of support or what!? :)

Could you try this with #328?

**Comment by ggalmazor** [comment]
The alternative placement won't work with screen sizes smaller than ~950 px wide, and #328 should make it not overlap any content, which prevents any problem due to small screen sizes.

Taking all this into consideration, do you think we should make the change for the alternative placement?
