### ISSUE TITLE
Sending the same submissions twice causes duplicates on Aggregate and other services.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#331]
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v1.x.x, Java vx.x.x, ... GAE/tomcat

#### Problem description
Sending the same submissions twice causes duplicates on Aggregate when use Birds form. 

#### Steps to reproduce the problem
1. Send the same submission of Birds form from Collect to Aggregate

#### Expected behavior
Submission should not be duplicated on Aggregate.

#### Other information 
Submissions of Birds are also duplicated when publishing results to json server and google services.
Used form: 
[Birds.zip](https://github.com/opendatakit/aggregate/files/2494883/Birds.zip)

**Comment by ggalmazor** [comment]
Key piece of information: the Birds form doesn't have a `meta` block with an `instanceId`. 

Having dupes when a form lacks of a `meta.instanceID` is a known issue we can't do much about.

I think this issue should be transformed into an action point to update the sample forms and ensure all of them have a `meta.instanceID`.

**Comment by lognaturel** [comment]
Agreed!
