### ISSUE TITLE
Wrong last update date format in submission cursor XML 

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#341]
Aggregate is formatting the last update date like `2018-12-10T09:36:25.474+0000` (notice how there's a missing colon in the offset) instead of `2018-12-10T09:36:25.474+00:00`

**Comment by sd1998** [comment]
@ggalmazor Can I work on this?

**Comment by ggalmazor** [comment]
Sure, @sd1998. I'd suggest you wait until #451 is done, though.

**Comment by ggalmazor** [comment]
I think you've a green light for working on this, @sd1998 :) Thanks!

**Comment by sd1998** [comment]
@ggalmazor Could you help me in reproducing this issue? Thanks.

**Comment by ggalmazor** [comment]
Hi, @sd1998, after thinking about this one, I'd prefer to close this issue. 

After reviewing the pull process in Briefcase (which is related to how download cursors are handled) I don't see any value on changing this in Aggregate at this moment.

Sorry for the confusion!
