### ISSUE TITLE
Remove Fusion Tables support

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#342]
Google is "turning down" FT in one year. It doesn't make sense to do a v2.0 release that includes FT code and features.

User facing changes:
- We don't give user the option to create new FT publishers
- We disable any existing publishers but maintain their entries in the publishers table so that links are still shown and work.
- When Google completely and definitively shuts down FT:
  - We remove the entries from the publishers table

Code changes:
- Remove everything that's not bolted to the floor, throw away anything we can dispose of:  It's hard to tell at this stage, but this includes a library and some classes

**Comment by yanokwa** [comment]
Can you be a little more specific here? Do you want to remove creation of new FT publishers? Disable existing publishers? Remove existing publishers?

**Comment by ggalmazor** [comment]
Closed by #348
