### ISSUE TITLE
Version number is hard coded in UIConsts.java

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#355]
In `src/main/java/org/opendatakit/aggregate/constants/common/UIConsts.java:20`,  `VERSION_STRING` is hard coded to "v1.4.15 Production".

We use this in `src/main/java/org/opendatakit/common/security/Realm.java:51` which is printed in the log. That value is also stored at `installer/installBuilder/buildWar.xml` which might be a problem as well.

Found this bug here: https://forum.opendatakit.org/t/increasing-ram-for-aggregate-on-app-engine/16830

**Comment by ggalmazor** [comment]
Thanks for pointing this out.

The version number in the `buildWar.xml` file gets overwritten by the Gradle task that builds the installer.
