### ISSUE TITLE
Unable to Get Blank Form when using Aggregate 2.0

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#363]
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v2.0.x, Java vx.x.x, ...

#### Problem description
Unable to Get Blank Form when using Aggregate 2.0. Screenshot of the displayed error message:
![screenshot_20181227-112456](https://user-images.githubusercontent.com/33342488/50508030-5b939100-0a80-11e9-8bf8-b4706cbbf9ad.png)

#### Steps to reproduce the problem
1. In Collect: General Settings/Server input aggregate's 2.0 url and your credentials
2. Go to Get Blank Form

#### Expected behavior
No error message should display. The user should be able to download a form and see the list of the forms.

#### Other information 
Sending finalized submissions works well.

**Comment by ggalmazor** [comment]
Closing. This is the same as #364.
