### ISSUE TITLE
Suggest users to migrate accounts to normal ODK type accounts

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#368]
https://github.com/opendatakit/aggregate/pull/350 has a comment that I want to make sure we don't forget.

> Also, during installation, we should suggest users to either migrate accounts to normal ODK type accounts or remove their google account credentials.

**Comment by ggalmazor** [comment]
![image](https://user-images.githubusercontent.com/205913/51026077-02eaea80-158e-11e9-9dd4-45c889e22927.png)
