### ISSUE TITLE
Date format difference on purging confirmation dialog windows.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/aggregate#370]
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v1.x.x, Java vx.x.x, ...

#### Problem description
There is a difference in the date format on purging confirmation dialog windows. 
When purge submission data, it is displayed like:
![screenshot from 201_purge submissions](https://user-images.githubusercontent.com/33342488/50896558-9f37b480-1409-11e9-8730-66afe0b3a457.png)
and when purging published data:
![screenshot from 2019-01_purge published data](https://user-images.githubusercontent.com/33342488/50896572-aa8ae000-1409-11e9-9c27-24c401786cb9.png)

#### Steps to reproduce the problem
Purge Published Data and Purge Submission Data compare the date form on confirmation dialog windows.

#### Expected behavior
Both data form should be the same.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by ggalmazor** [comment]
This is annoying: GWT doesn't emulate `java.time`. I'll have to emulate the format using GWT's `DateTimeFormat` class instead of reusing `JRTemporal`:|
