### ISSUE TITLE
I want to upload XML files through Python code. Is there any special interface or other solution?

### ISSUE THREAD

**Issue by guxiaowei** [opendatakit/aggregate#378]
#### Software and hardware versions 
Windows, Aggregate v1.x.x, Java vx.x.x, ...

#### Problem description
I want to upload XML files through Python code. Is there any special interface or other solution?
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by ggalmazor** [comment]
Hi @guxiaowei! 

Support questions should be sent to the [support forum](https://forum.opendatakit.org/c/support). Please, create a new post there and try to add as much information as you can: what's your environment, what have you tried, attach any form you're using, log files, etc.
