### ISSUE TITLE
Pulling forms doesn't work behind a proxy/load balancer

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#402]
The Cloud-Config stack configures Aggregate to dynamically set the server's hostname on startup, which will produce http://127.0.0.1 URLs when Collect/Briefcase try to pull forms.

The solution is to configure the hostname with whatever IP or domain final users see, but this currently triggers an infinite HTTP 302 redirection loop (addressed in #401)

This issue will keep track of this while we work out a solution for #401

**Comment by yanokwa** [comment]
I think this can be closed, @ggalmazor. If you agree, please close.
