### ISSUE TITLE
Force package upgrades in Cloud-Config stacks

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#411]
The Cloud-Config stacks report on login:

```
45 packages can be updated.
11 updates are security updates.
```

Should we take care of upgrading the packages after completing the installation so that those security updates get installed?

**Comment by yanokwa** [comment]
We have unattended upgrades on the VM and I think we should do that on the cloud-config.
https://github.com/opendatakit/aggregate/blob/master/packer/ansible/roles/unattended-upgrades/tasks/main.yml

We should maybe warn people in the docs that we do that in case it breaks something. But it's typically very very safe.

**Comment by yanokwa** [comment]
This should be as easy as adding `unattended-upgrades` to runcmd. I've confirmed that Ubuntu comes with that app installed and it is configured to only install security updates.
