### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by foranastes** [opendatakit/aggregate#412]
#### Software and hardware versions 
Centos 7, Tomcat 8

#### Problem description
I'm getting 404 error after upgrading to 2.0.

#### Steps to reproduce the problem
Delete old Aggregate.war file and Past the new One

**Comment by ggalmazor** [comment]
Hi @foranastes. I'm sorry you're having trouble with 2.0, but support questions should be sent to the [Support Forum](https://forum.opendatakit.org/c/support).

Please, add more detail about what was your previous situation (operating system, Aggregate version you were running) and what specific steps you followed to perform the upgrade.
