### ISSUE TITLE
Authenticate users by checking ODK Database

### ISSUE THREAD

**Issue by guxiaowei** [opendatakit/aggregate#424]
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v1.x.x, Java vx.x.x, ...

#### Problem description
Hi there,

I would like to authenticate my current ODK users from another mini web-app
by directly checking the ODK db.

How do I generate the digest hash that is saved on _registered_users table?
I'm not sure in what java files ODK generates the hashes,, whether it uses
some salt.

and i want to know where the code control user authentication in odk aggregate

Thanks,

**Comment by ggalmazor** [comment]
Hi, @guxiaowei!

Support questions like the one you have should be sent to the [Support forum](https://forum.opendatakit.org/c/support). Please, open a new topic there so that the answer can help other users as well.
