### ISSUE TITLE
Upgrade from 1.7.1 to 2.0.0 fails.

### ISSUE THREAD

**Issue by mathieubossaert** [opendatakit/aggregate#429]
#### Software and hardware versions 
Linux (Docker), Aggregate v1.7.1 over tomcat:alpine (8.5.38-jre8), postgresql 10.7

#### Problem description
I upgrade from 1.5.0 to 1.6.1 to 1.7.0 to 1.7.1 without a problem but I can't upgrade to 2.0

#### Other information 
logs mention that problem : 
"Could not resolve placeholder 'jdbc.driverClassName' in string value "${jdbc.driverClassName}""

Thank's a lot.

**Comment by yanokwa** [comment]
https://forum.opendatakit.org/t/odk-aggregate-v2-00-possible-bug-in-generated-war-file/18199 looks like the same problem.

**Comment by ggalmazor** [comment]
Hi, @mathieubossaert!

If I'm not mistaken, you're compiling Aggregate yourself. If so, notice that we've improved the way we handle conf files to avoid pushing modified conf files (with changes for a particular dev's environment). Now, you there's no default conf files in the repo and you can use some `.example` files at `src/main/resources` as a template. 

The example files should work if your setup is exactly the same as the described in the README's instructions.

Please, let me know if this is what was giving you trouble.

**Comment by mathieubossaert** [comment]
Hi @ggalmazor,

no I am using the installer. Java lessons are too far from me, but one day, I promise, I will compile Aggregate from sources ;-)

Thanks.

**Comment by ggalmazor** [comment]
Thanks, @mathieubossaert!

In the meantime, I was checking the installer and I think I've found what's causing the problem. I think we will have to replace the installer for the v2.0 release. The code is OK, but apparently, there are some missing adaptations in the installer from v1.x to v2.0

**Comment by ggalmazor** [comment]
Hi, @mathieubossaert!

I've created a PR with the fix for the installer. While we review, test, and release it, would you be up for beta testing the installer if I attach here one built by me? If so, which operating system are you running?

**Comment by mathieubossaert** [comment]
of course I can.
I run aggregate into a tomcat:alpine docker container.

**Comment by ggalmazor** [comment]
OK, then I need to check more stuff. I'll get back to you about this :)

**Comment by mathieubossaert** [comment]
"v2.0.0 - You're up to date!"

Thanks a lot Gulliermo !

**Comment by ggalmazor** [comment]
Awesome! Thanks for testing it ;)

**Comment by ggalmazor** [comment]
Closed by #422
