### ISSUE TITLE
Validate JSON publisher url

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/aggregate#436]
#416 introduces validation on the publisher creation forms.

The JSON publisher form only checks that the user enters something in the url field. We should also verify that it's a valid URL string.

**Comment by kkrawczyk123** [comment]
I am a fan of the idea of adding validation for valid URL. My other suggestion is to leave the content of that filed empty as default, means remove the current "http://localhost" content. The user can click Publish button just with the default content, adding validation will solve that for sure. But still, publishing servers do not have to be a local one in all cases. What are your opinions on that @ggalmazor and @yanokwa :)

**Comment by sd1998** [comment]
@ggalmazor Can I work on this?

**Comment by ggalmazor** [comment]
Sure, @sd1998!

Let me sum up what has to be done to the JSON Server publisher dialog:
- Add validation to the URL field
- Remove the default value "http://localhost"
