### ISSUE TITLE
Aggregate should not block page loads when network is down

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/aggregate#459]
#### Software and hardware versions 
Aggregate v2.0.2

#### Problem description
If you run Aggregate with the network down, the front page does not load. The two network calls that I can see are
* For maps.googleapis.com/maps/api/js in AggregateHTMLServlet.java 
* For api.github.com in LayoutUtils.java

#### Potential solutions
* Add async and defer to Google maps call as shown in the docs at https://developers.google.com/maps/documentation/javascript/tutorial
* If the XMLHttpRequest call fails, return a versionNote of "Version check failed" rather than blocking the UI.

**Comment by ggalmazor** [comment]
Thanks for the research. That will make the fix much easier for me :)
