### ISSUE TITLE
Incorrect war file in v2.0.3 release

### ISSUE THREAD

**Issue by gkilleen33** [opendatakit/aggregate#468]
#### Software and hardware versions 
Aggregate v2.0.3

#### Problem description
The .war file uploaded with the v2.0.3 release appears to be from v2.0.2. This also stops updating via the `sudo aggregate-cli -c /root/aggregate-config.json -u` command from working because the url that it attempts to curl does not exist.

#### Steps to reproduce the problem
From Aggregate v2.0.2 enter `sudo aggregate-cli -c /root/aggregate-config.json -u`

I also tried manually adding the .war file included with the release, and it lists as v2.0.2 on the console. So I think it is the incorrect file and not just a naming issue.

#### Expected behavior
This command should update Aggregate to v2.0.3

**Comment by ggalmazor** [comment]
Thanks for reporting this, @gkilleen33, and apologies for the dumb mistake. I'm replacing the WAR file now

**Comment by ggalmazor** [comment]
So, the problem was that I uploaded the correct WAR but gave it the wrong name. I've verified that the WAR file belongs to the v2.0.3 release.

I've fixed the name and now `aggregate-cli` should update Aggregate correctly.
