### ISSUE TITLE
Geotrace and Geoshape points are lost because of the maximum number of characters is 255

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/aggregate#471]
#### Software and hardware versions 
Aggregate v1.20, v1.17

#### Problem description
Geotrace and Geoshape points are lost because of the maximum number of characters is 255

#### Steps to reproduce the problem
1. The user fills the form on Collect [Geo.xml.txt](https://github.com/opendatakit/aggregate/files/3256266/Geo.xml.txt)
2. The user adds ~10 points to Geotrace and Geoshape (number of points depends on device accuracy)
3. The user sends the submission to Aggregate
4. Not all point are visible in Aggregate
![Screenshot from 2019-06-05 10-47-04](https://user-images.githubusercontent.com/3907554/58943113-61a04300-877f-11e9-89ef-d0e665c67541.png)

#### Expected behavior
Data loss does not occur

#### Other information 
Problem reported on forum : https://forum.opendatakit.org/t/number-of-points-i-can-collect-when-using-geotrace-function/20244

**Comment by ggalmazor** [comment]
Hi, @mmarciniak90!

The attached form doesn't define `odk:length` attributes in the geo field bindings as instructed in https://docs.opendatakit.org/aggregate-field-length/

I've added a comment in the forum post to let the user know about this.
