### ISSUE TITLE
Geotrace and Geoshape points are lost because of the maximum number of characters is 255

### ISSUE THREAD

**Issue by mylesmcd** [opendatakit/aggregate#473]
Hi all,
My issue relates closely to #471.
We are trying to collect trace data but are hitting the 255 character limit.
I attach to this issue an xml that uses the suggested odk:length syntax.
In our case I have set the length to 50000.

Here is the xml of a test project:
[test_polytrace3.txt](https://github.com/opendatakit/aggregate/files/3279991/test_polytrace3.txt)

When I check this table in Postgis the odk:length instruction works for the field with size 99 but not for the 50000 length field, which is fixed at 255. See attached screenshot of the table definition SQL.

![bad_field_sizes_2](https://user-images.githubusercontent.com/15659828/59330603-bdd10d00-8d13-11e9-823c-145684880553.JPG)

Until this is fixed we have to use a very labourious workaround...
Best,
Myles

**Comment by mathieubossaert** [comment]
Hi,

I don-t know the workaround you use but you can increase the length of the field to prevent such a problem.
https://docs.opendatakit.org/aggregate-field-length/

**Comment by ggalmazor** [comment]
Thanks for answering, @mathieubossaert. That's the way to work around this problem.
